apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-proxy
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-proxy
  template:
    metadata:
      labels:
        app: micro-proxy
    spec:
      containers:
      - name: micro-proxy
        image: micro-proxy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: micro-proxy
spec:
  selector:
    app: micro-proxy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 5000